DROP TABLE IF EXISTS challenge_records CASCADE;

-- CREATE CHALLENGE RECORDS
CREATE TABLE challenge_records (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE NOT NULL,
  challenge_id INTEGER NOT NULL REFERENCES challenges(id) ON DELETE CASCADE NOT NULL
);