-- INSTRUCTION FOR MANUALS
INSERT INTO trick_instructions (trick_id, title, instruction) VALUES (1, 'Find a Suitable Area', 'Start in an open and flat area with a smooth surface. It''s important to practice in a safe environment to avoid accidents.');
INSERT INTO trick_instructions (trick_id, title, instruction) VALUES (1, 'Foot Placement', 'Stand on your skateboard with your front foot placed in the middle of the deck, perpendicular to the board. Your back foot should be placed on the tail, angled diagonally.');
INSERT INTO trick_instructions (trick_id, title, instruction) VALUES (1, 'Start Riding', 'Push off with your back foot to gain some speed. As you start moving, keep your weight centered over the skateboard and get comfortable riding.');
INSERT INTO trick_instructions (trick_id, title, instruction) VALUES (1, 'Shift Your Weight', 'As you gain some speed, shift your weight towards the tail of the skateboard by leaning slightly back. Your front foot should become lighter, and your back foot''s pressure on the tail will raise the front wheels off the ground.');
INSERT INTO trick_instructions (trick_id, title, instruction) VALUES (1, 'Balancing Act', 'Finding the right balance point is crucial. Use your arms for balance, spreading them out to the sides. Keep your gaze forward to maintain balance.');
INSERT INTO trick_instructions (trick_id, title, instruction) VALUES (1, 'Control', 'To maintain the manual, make small adjustments with your body and arms. If the front end of the skateboard starts to dip, shift your weight slightly forward. If the back end starts to dip, shift your weight backward.');
INSERT INTO trick_instructions (trick_id, title, instruction) VALUES (1, 'End the Manual', 'To end the manual, gently shift your weight forward to lower the front wheels back to the ground. You can also practice "popping" the front wheels back down by shifting your weight forward while tapping the tail on the ground.');

-- INSTRUCTION FOR OLLIES
INSERT INTO trick_instructions (trick_id, title, instruction) VALUES (2, 'Foot Positioning', 'Place your back foot perpendicular to the tail of the skateboard. The ball of your foot should be centered on the tail edge, with your toes hanging slightly over the edge. Position your front foot diagonally across the skateboard, with the ball of your foot near or just behind the front bolts. Your toes should point slightly towards the skateboard''s nose.');
INSERT INTO trick_instructions (trick_id, title, instruction) VALUES (2, 'Prepare to Ollie', 'Bend your knees slightly to prepare for the jump. Lean your weight slightly back towards the tail of the skateboard.');
INSERT INTO trick_instructions (trick_id, title, instruction) VALUES (2, 'The Pop', 'Use your back foot to forcefully stomp down on the tail of the skateboard, popping it against the ground. As you pop the tail down, simultaneously slide your front foot up towards the skateboard''s nose. This sliding motion is crucial for leveling out the board in the air.');
INSERT INTO trick_instructions (trick_id, title, instruction) VALUES (2, 'Jump', 'Just as the skateboard begins to rise, jump off the ground with both feet. This will help you lift the board higher into the air. Bring your knees up towards your chest to maximize the height of the ollie.');
INSERT INTO trick_instructions (trick_id, title, instruction) VALUES (2, 'Leveling Out', 'As the skateboard reaches its highest point, use your front foot to level it out. Push your front foot forward and level it with your back foot. Keep your body centered over the skateboard to maintain balance.');
INSERT INTO trick_instructions (trick_id, title, instruction) VALUES (2, 'Landing', 'As the skateboard starts to descend, prepare to absorb the impact by slightly bending your knees. Aim to land both feet squarely on the bolts, which are the metal parts connecting the wheels to the skateboard. Try to land with your weight centered over the skateboard to maintain stability.');
INSERT INTO trick_instructions (trick_id, title, instruction) VALUES (2, 'Roll Away', 'Once you''ve landed, bend your knees and regain your balance. Start rolling forward by pushing with your back foot or by shifting your weight to start pushing with your front foot. Continue riding and practice the ollie consistently to improve your technique and height.');
